	<link href="<?= $rpath ?>libs/bootstrap-5.2.2-dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="<?= $rpath ?>libs/bootstrap-icons-1.10.2/bootstrap-icons.css" rel="stylesheet">
<?php if (isset($has_discussion) && $has_discussion === TRUE) : ?>
	<link href="<?= $rpath ?>libs/viewerjs-1.11.2/dist/viewer.css" rel="stylesheet">
	<link href="<?= $rpath ?>libs/video-js-7.20.3/video-js.min.css" rel="stylesheet">
	<link href="<?= $rpath ?>libs/leaflet/leaflet.css" rel="stylesheet" />
	<link href="<?= $rpath ?>libs/Leaflet.fullscreen-1.0.2/dist/leaflet.fullscreen.css" rel="stylesheet" />
<?php endif; ?>
